refactor host OS configuration
intel/container-experience-kits pull request #45
Opened 2020-02-25 14:03 UTC by przemeklal

* split k8s-all-preconfigure and k8s-node-preconfigure roles into smaller roles and move them to roles/bootstrap/ directory
* add support for iavf drivers update
* move sriov-nic-init, install-ddp-pkgs and install-dpdk from post-kubernetes playbook to host OS configuration playbook
* rename infra.yml to advanced.yml to prepare for further playbooks split up
* rename dpdk-install to install-dpdk
* make sriov_numvfs configuration persistent
* remove unncessary space from the task names
* update kubespray to latest version from master

2020-02-28 08:41 UTC, przemeklal commented
Ready for review/merge.

2020-02-28 13:22 UTC, przemeklal commented
rebased to include bond-cni in the refactored code

2020-03-05 15:57 UTC, davecremins commented
I think we need to include some extra details in the readme that explains our intentions with the breakout of concerns i.e. infra/host, k8s, capabilities

2020-04-02 11:22 UTC, przemeklal commented
rebased on top of PR #63

2020-04-08 23:00 UTC, jagibso2 requested changes

2020-04-08 23:00 UTC, jagibso2 commented on roles/bootstrap/update-nic-drivers/tasks/main.yml
> +  when: force_nic_drivers_update | default(false) | bool
skip if mgmt interface is i40e

2020-04-08 23:00 UTC, jagibso2 commented on roles/bootstrap/update-nic-drivers/tasks/main.yml
> +  when: force_nic_drivers_update | default(false) | bool
same as above

2020-04-08 23:00 UTC, jagibso2 commented on roles/bootstrap/update-nic-drivers/tasks/main.yml
> +  when: force_nic_drivers_update | default(false) | bool
same as above

2020-04-09 08:20 UTC, przemeklal commented on roles/bootstrap/update-nic-drivers/tasks/main.yml
> +  when: force_nic_drivers_update | default(false) | bool
+1, will do

2020-04-09 10:16 UTC, przemeklal commented on roles/bootstrap/update-nic-drivers/tasks/main.yml
> +  when: force_nic_drivers_update | default(false) | bool
done

2020-04-09 10:16 UTC, przemeklal commented on roles/bootstrap/update-nic-drivers/tasks/main.yml
> +  when: force_nic_drivers_update | default(false) | bool
done

2020-04-09 10:17 UTC, przemeklal commented on roles/bootstrap/update-nic-drivers/tasks/main.yml
> +  when: force_nic_drivers_update | default(false) | bool
done

2020-04-09 18:40 UTC, jagibso2 approved these changes

2020-04-16 13:16 UTC, merged